name: Trigger auto deployment for elxcontainerapp1110

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/elxcontainerapp1110-AutoDeployTrigger-20a99e61-aee8-407c-8e98-559b9b3c4a7a.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ELXCONTAINERAPP1110_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrlinuxwebapp.azurecr.io
          registryUsername: ${{ secrets.ELXCONTAINERAPP1110_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ELXCONTAINERAPP1110_REGISTRY_PASSWORD }}
          containerAppName: elxcontainerapp1110
          resourceGroup: elxcontainerapp
          imageToBuild: acrlinuxwebapp.azurecr.io/elxcontainerapp1110:${{ github.sha }}
          

     

